//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScotiaSuppliersAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int TicketId { get; set; }
        public string CustomerId { get; set; }
        public int Product_ProductId { get; set; }
        public int Product_SupplierId { get; set; }
        public string Status { get; set; }
        public string TrackingId { get; set; }
    
        public virtual product product { get; set; }
    }
}
