//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScotiaSuppliersAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.orders = new HashSet<order>();
        }
    
        public int ProductId { get; set; }
        public int SupplierId { get; set; }
        public string Name { get; set; }
        public float MoneyPrice { get; set; }
        public int PointsPrice { get; set; }
        public string Description { get; set; }
        public int AQuantity { get; set; }
        public string ImageUrl { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<order> orders { get; set; }
        public virtual supplier supplier { get; set; }
    }
}
