//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScotiaSuppliersAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier
    {
        public supplier()
        {
            this.products = new HashSet<product>();
        }
    
        public int SupplierId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int ProductsType { get; set; }
        public string Status { get; set; }
        public string ImageUrl { get; set; }
    
        public virtual ICollection<product> products { get; set; }
    }
}
